// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed LabGrotesque-Bold.ttf
var resourceLabGrotesqueBoldTtfData []byte
var resourceLabGrotesqueBoldTtf = &fyne.StaticResource{
	StaticName:    "LabGrotesque-Bold.ttf",
	StaticContent: resourceLabGrotesqueBoldTtfData,
}
